language: python
python:
  - "3.6"  

services:
  - postgresql

env:
  global:
    - FLASK_ENV = TESTING
before_script:
  - psql -c "create database challengethree_test;" -U postgres
  - export 'DB-NAME' = "challengethree_test"

install:
  - pip install -r requirements.txt

script:
  - pytest --cov
  - coverage report
after_success:
  - coveralls

notifications:
email: false