language: python
python:
  - "3.6"  

services:
  - postgresql

env:
  global:
    - APP_SETTINGS = test_env
before_script:
  - psql -c "create database challengethree_test;" -U postgres

install:
  - pip install -r requirements.txt

script:
  - pytest --cov
  - coverage report
after_success:
  - coveralls

notifications:
email: false